- cypress/integration/features/helpAreas.feature
- cypress/support/pages/help/pageHelp.js
- cypress/support/step_definition/help/help.spec.js
Added remaining tests for help area.
More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)
> added remaining tests for help area

- cypress/integration/features/course/editCourse.feature
- cypress/support/pages/course/pageEditCourse.js
- cypress/support/step_definition/course/createCourse/createCourse.spec.js
- cypress/support/step_definition/course/editCourse/editCourse.spec.js
Implemented new test "Add class to course" and also implemented "Remove classes from course".
In createCourse.js I removed a unused When-sequence.
> Add class to course

- .github/workflows/automatic-trigger.yml
- .github/workflows/manual-trigger.yml
- .gitignore
- cypress.json
- cypress/support/commands.js
- cypress/support/custom_commands/login.js
- package-lock.json
- package.json
In this PR, we separate user credentials and environment variables into different file named as `cypress.env.json`. We did not included it in our repo as its contains sensitive details about the test users we are using. Such way we can have different configurations in our local without breaking anything in CI. Also updated in this PR, YML files and `login.js`.
https://ticketsystem.dbildungscloud.de/browse/BC-1813
https://ticketsystem.dbildungscloud.de/browse/BC-1835
> BC-1813- Hiding environment variables

- cypress.json
- cypress/support/pages/course/pageCommonCourses.js
- config update (quick fix to test)
> updated some config page load

- .github/workflows/manual-trigger.yml
- updated testing default urls in manual trigger workflow.
> update testing urls in manual trigger yml

- cypress/integration/features/course/createAndDeleteCourse.feature
- cypress/integration/features/task/createAndDeleteTask.feature
- cypress/support/pages/course/pageCommonCourses.js
- cypress/support/step_definition/course/createAndDeleteCourseSteps.spec.js
The first in development tasks was to change the "Go to room"-steps so that they are independent from userlanguage. 
This should be merged before creating the task features because it is used also by other test features.
> Bc 1874 creation and deletion of tasks

- .github/workflows/scheduled-trigger.yml
https://ticketsystem.dbildungscloud.de/browse/BC-2070
- added RC integration yml
> added RC notification yml config

- .github/workflows/manual-trigger.yml
- .github/workflows/scheduled-trigger.yml
- updated yml for RC integration.
> updated yml

- .github/workflows/manual-trigger.yml
- follow-up fix on RC integration
> updated rc yml

- cypress/integration/features/task/createAndDeleteTask.feature
- cypress/integration/features/task/createEditAndDeleteTask.feature
- cypress/support/pages/course/pageCommonCourses.js
- cypress/support/pages/tasks/pageTasks.js
- cypress/support/step_definition/course/commonCourseSteps.spec.js
- cypress/support/step_definition/tasks/createAndDeleteTasks.spec.js
- cypress/support/step_definition/tasks/createEditAndDeleteTasks.spec.js
- package-lock.json
- package.json
* Added scenario for editing task.
* installed Cypress Upload package
- https://ticketsystem.dbildungscloud.de/browse/BC-2170
> Bc 1874 edit publish task

- cypress/integration/features/task/createEditDeleteSubGradFinishRestoreTask.feature
- cypress/support/pages/tasks/pageTasks.js
- cypress/support/step_definition/tasks/createEditDeleteSubGradFinishRestoreTask.spec.js
Added Student sees grading scenario
> BC 2316 cy student sees teachers grading

- .github/workflows/automatic-trigger.yml
- .github/workflows/manual-trigger.yml
- .github/workflows/scheduled-trigger.yml
- cypress/integration/features/account/goToSettings.feature
- cypress/support/custom_commands/login.js
- cypress/support/pages/login_management/pageLoginManagement.js
- cypress/support/pages/tasks/pageTasks.js
> Refactor for login 

- cypress/support/custom_commands/login.js
- cypress/support/pages/login_management/pageLoginManagement.js
- cypress/support/step_definition/addons/goToAddonsSteps.spec.js
- cypress/support/step_definition/course/createEditAndDeleteCourseSteps.spec.js
- cypress/support/step_definition/course/searchingCourseSteps.spec.js
- cypress/support/step_definition/dashboard/dashboardSteps.spec.js
- cypress/support/step_definition/help_section/helpAreasSteps.spec.js
- cypress/support/step_definition/login_management/forgotPasswordDialogSteps.spec.js
- cypress/support/step_definition/management/admin_management/administrateExternalToolsSteps.spec.js
- cypress/support/step_definition/management/admin_management/administrateUsersSteps.spec.js
- cypress/support/step_definition/news/commonNewsSteps.spec.js
- cypress/support/step_definition/news/readNewsSteps.spec.js
- cypress/support/step_definition/teams/commonTeamsSteps.spec.js
https://ticketsystem.dbildungscloud.de/browse/BC-2588
- Removed unexpected cy assertion from  showUpElementsOnDialog() method.
- Refactor/clean up comments in step definitions.
> BC-2588 clean up tests comment and unused assertion in password dialog box

- cypress/integration/features/teams/createEditDeleteTeam.feature
- cypress/support/pages/teams/pageCommonTeams.js
- cypress/support/pages/teams/pageTeams.js
- cypress/support/step_definition/teams/createEditDeleteTeamSteps.spec.js
BC-2667
- Added a new test to create, edit and delete team.
> Bc 2667 e2e teams

- cypress/integration/features/dashboard/dashboard.feature
- cypress/integration/features/files/myFiles.feature
- cypress/integration/features/news/readNews.feature
- cypress/support/pages/files/pageFiles.js
- cypress/support/step_definition/files/myFiles.spec.js
- Added more assertion in files test 
- Remove race conditions between Dashboard and News tests
https://ticketsystem.dbildungscloud.de/browse/BC-3019
> BC 3019 add more assertions in files feature

- cypress/support/pages/tasks/pageTasks.js
> two methods fixed

- cypress/integration/features/account/changeLanguage.feature
- cypress/support/pages/account/pageAccount.js
- cypress/support/step_definition/account/changeLanguageSteps.spec.js
In this PR, added test cases for language change for all users (teacher, admin & students)
https://ticketsystem.dbildungscloud.de/browse/BC-1895
> BC 1895 change language feature

- .github/workflows/automatic-trigger.yml
- .github/workflows/manual-trigger.yml
- .github/workflows/scheduled-trigger.yml
BC-3272
- To try the tests running sequentially, the parallelization max value is set to 1 
- To update the scheduled trigger to 4:00 AM (everyday)
> set the max parallel value to 1

- .github/workflows/automatic-trigger.yml
- .github/workflows/manual-trigger.yml
- .github/workflows/scheduled-trigger.yml
- cypress/integration/features/topics/createEditDeleteTopic.feature
- package.json
https://ticketsystem.dbildungscloud.de/browse/BC-3434
- Applied stable tag on the 'topics' related tests set.
> updated the tag

- cypress/integration/features/login_management/brokerLogin.feature
- cypress/support/pages/login_management/pageLoginManagement.js
- cypress/support/step_definition/login_management/commonLoginManagementSteps.spec.js
https://ticketsystem.dbildungscloud.de/browse/BC-3448
- Test dependency on button label in removed on the keycloak login button (in case label changes again in the future), whereas only data-testid is kept/used for assertion.
> adapted change in keycloak login button

- cypress/integration/features/course/createEditAndDeleteCourse.feature
- cypress/support/pages/course/pageCourses.js
- cypress/support/step_definition/course/createEditAndDeleteCourseSteps.spec.js
> data-testids english and split up some tests

- cypress/e2e/help-section/helpAreas.feature
- cypress/support/pages/help_section/pageHelpSection.js
- https://ticketsystem.dbildungscloud.de/browse/BC-3536
- https://github.com/hpi-schul-cloud/schulcloud-client/pull/3154
> BC-3536-adapt existing test to BC-2999-selecting section is mandatory now

- .github/workflows/automatic-trigger.yml
- .github/workflows/manual-trigger.yml
- .github/workflows/scheduled-trigger.yml
https://ticketsystem.dbildungscloud.de/browse/BC-3603
- Video artifact path is updated after updating v12
- Scheduled test time is set to 1:00 am as Github is in UTC, so to run test earlier/nightly
> Bc 3603 video artifact cy12

- cypress/e2e/task/createDeleteTaskFromTaskPage.feature
- cypress/e2e/task/createEditDeleteSubGradFinishRestoreTask.feature
- cypress/support/pages/course/pageCourses.js
- cypress/support/pages/tasks/pageTasks.js
- cypress/support/step_definition/authentication/loginStep.spec.js
- cypress/support/step_definition/tasks/commonTaskSteps.spec.js
cy.waits added to first 3 scenarios of task test 
> Bc 3608 add interceptions to task test

- cypress/e2e/task/createDeleteTaskFromTaskPage.feature
- cypress/support/pages/tasks/pageTasks.js
- cypress/support/step_definition/tasks/commonTaskSteps.spec.js
https://ticketsystem.dbildungscloud.de/browse/BC-3675
> Bc 3675 adapt changes in task overview button

- .github/workflows/automatic-trigger.yml
- .github/workflows/manual-trigger.yml
- .github/workflows/scheduled-trigger.yml
- cypress/e2e/course/addSubstituteTeacherToCourse.feature
- cypress/support/pages/course/pageCourses.js
- cypress/support/step_definition/course/commonCourseSteps.spec.js
- https://ticketsystem.dbildungscloud.de/browse/BC-3695
> BC-3695-Test: Add substitute teacher to course

- cypress/e2e/dashboard/dashboard.feature
- cypress/support/custom_commands/login.js
- cypress/support/pages/dashboard/pageDashboard.js
- cypress/support/pages/news/pageNews.js
- cypress/support/pages/teams/pageTeams.js
- cypress/support/step_definition/authentication/loginStep.spec.js
- cypress/support/step_definition/teams/commonTeamsSteps.spec.js
https://ticketsystem.dbildungscloud.de/browse/BC-3739
- Applied assertions on the visiting page in the test as an indicator to make sure page is loaded successfully (on dashboard.feature) 
- removed some of the api wait().
- added a new step in the dashboard.feature
> BC-3739-added-assertions-as-page-load-indicator

- cypress.config.js
https://ticketsystem.dbildungscloud.de/browse/BC-3667
- testIsolation parameter is set to false in the config to avoid redundant clearing the cookies, local storage etc. as we are using cy.session() which is inheriting the testIsolation property by default as enabled/true in v12.
> BC-3667 test isolation config v12 (cookies, local storage etc)

- cypress/e2e/course/addSubstituteTeacherToCourse.feature
- cypress/e2e/course/createEditAndDeleteCourse.feature
- cypress/e2e/dashboard/dashboard.feature
- cypress/e2e/files/myFiles.feature
- cypress/e2e/teams/teacherAddsEditsDeleteTeamEventWithVideoConference.feature
- cypress/support/pages/admin/pageAdministration.js
- cypress/support/pages/course/pageCourses.js
- cypress/support/pages/files/pageFiles.js
- cypress/support/pages/help_section/pageHelpSection.js
- cypress/support/pages/login_management/pageLoginManagement.js
- cypress/support/pages/news/pageNews.js
- cypress/support/pages/tasks/pageTasks.js
- cypress/support/pages/teams/pageTeams.js
- cypress/support/step_definition/admin/administrateUsersSteps.spec.js
- cypress/support/step_definition/course/commonCourseSteps.spec.js
- cypress/support/step_definition/files/myFiles.spec.js
- cypress/support/step_definition/teams/commonTeamsSteps.spec.js
- cypress/support/step_definition/teams/teacherAddsEditsDeleteTeamEventWithVideoConferenceSteps.spec.js
- https://github.com/hpi-schul-cloud/schulcloud-client/pull/3167
- https://ticketsystem.dbildungscloud.de/browse/BC-3002
- Fix applied on data-testid for the elements used in modal ( e.g. save, delete buttons in modals on different page)
- Adjusted some tests (feature file steps, methods, assertion data variables where not to be used like in files, adding team members)
- Updated data-testids where applicable in the methods/tests.
> Test Automation Error-> to investigate on how to put unique data-testid on certain elements

- .github/workflows/remote-trigger.yml
- cypress/e2e/account/changeLanguage.feature
- cypress/e2e/account/goToSettings.feature
- cypress/e2e/addons/goToAddons.feature
- cypress/e2e/admin/administrateExternalTools.feature
- cypress/e2e/admin/administrateUsers.feature
- cypress/e2e/course/addSubstituteTeacherToCourse.feature
- cypress/e2e/course/searchRoom.feature
- cypress/e2e/dashboard/dashboard.feature
- cypress/e2e/help-section/helpAreas.feature
- cypress/e2e/login_management/invalidCredentials.feature
- cypress/e2e/news/readNews.feature
- cypress/e2e/teams/studentCreateEditDeleteTeam.feature
- cypress/e2e/teams/teacherAddsEditsDeleteTeamEventWithVideoConference.feature
- cypress/e2e/teams/teacherCreateEditDeleteTeam.feature
[BC-4051](https://ticketsystem.dbildungscloud.de/browse/BC-4051)
- added remote yml config file, just a file to add further cinfiguration.
- removed @pr tag from the features not required to be run in pr pipeline
> BC-4051-adding remote trigger

- .github/workflows/remote-trigger.yml
- Only minor changes in remote-trigger.yml file
> Bc 4051 integration cy tests in pr pipeline

- cypress/e2e/task/createDeleteTaskFromTaskPage.feature
- cypress/e2e/task/createEditDeleteSubGradFinishRestoreTask.feature
- cypress/support/pages/tasks/pageTasks.js
- cypress/support/step_definition/tasks/commonTaskSteps.spec.js
https://ticketsystem.dbildungscloud.de/browse/BC-3868
https://ticketsystem.dbildungscloud.de/browse/BC-3858
> BC-3868 - Steps adapted to new process

- cypress/support/pages/account/pageAccount.js
https://ticketsystem.dbildungscloud.de/browse/BC-2762
- https://github.com/hpi-schul-cloud/dof_app_deploy/pull/526
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/4139
- https://github.com/hpi-schul-cloud/schulcloud-client/pull/3199
- https://github.com/hpi-schul-cloud/nuxt-client/pull/2541
- https://github.com/hpi-schul-cloud/end-to-end-tests/pull/438
> BC-2762 - rename ukrainian language key

- .github/workflows/remote-trigger.yml
- cypress/e2e/course/createEditAndDeleteCourse.feature
- cypress/e2e/files/myFiles.feature
- cypress/e2e/login_management/forgotPasswordDialog.feature
- cypress/e2e/login_management/passwordUpdate.feature
- cypress/e2e/task/createDeleteTaskFromTaskPage.feature
- cypress/e2e/topics/createEditDeleteTopic.feature
https://ticketsystem.dbildungscloud.de/browse/BC-4030
- Remote yml file is updated with further changes to be called from the remote repo (e.g. Old client).
- @pr tag is added to only two tests broker login and task tests.
> BC-4030-updated remote yml and pr reduced tests

- .github/workflows/remote-trigger.yml
> BC-4051 - check local branch

- .github/workflows/remote-trigger.yml
https://ticketsystem.dbildungscloud.de/browse/BC-4051
> BC-4051 Update remote trigger workflow

- cypress/support/pages/course/pageCourses.js
aria-label in UI has changed, so we had to adapt this test. For this a new data-testid was added and the method showRoomPage adapted.
https://ticketsystem.dbildungscloud.de/browse/BC-4582
> fixed createEditDeleteSubGradFinshRestoreTask-Test

- .github/workflows/remote-trigger.yml
- cypress/e2e/course/createEditAndDeleteCourse.feature
- cypress/support/pages/course/pageCourses.js
Update test case `createEditAndDeleteCourse`.
https://ticketsystem.dbildungscloud.de/browse/BC-4584
- `data-testid` is used instead of `aria-label`
-  Removed extra step in delete course section 
-  Corrected pre-condition state previously it was `brb` instead of `default`. whereas in later scenarios `default` is used
> BC 4584 update course test case

- README.md
- cypress/e2e/task/createDeleteTaskFromTaskPage.feature
- cypress/support/pages/tasks/pageTasks.js
- cypress/support/step_definition/tasks/commonTaskSteps.spec.js
Creating task on task overview page has been changed, so the test was failing. This is fixed now.
https://ticketsystem.dbildungscloud.de/browse/BC-4583
> fix task test and update readme

- cypress/e2e/teams/teacherAddsEditsDeleteTeamEventWithVideoConference.feature
- cypress/support/pages/teams/pageTeams.js
- cypress/support/step_definition/teams/teacherAddsEditsDeleteTeamEventWithVideoConferenceSteps.spec.js
https://ticketsystem.dbildungscloud.de/browse/BC-4815
> Bc 4815 fix team test with videoconf

- cypress/support/pages/account/pageAccount.js
https://ticketsystem.dbildungscloud.de/browse/BC-4919
> changed label of ukrainian language option

- .github/workflows/main.yml
- README.md
- package-lock.json
- package.json
> Cypress version upgrade

- cypress/e2e/course/createEditAndDeleteCourse.feature
- cypress/e2e/group/groupMembers.feature
- cypress/e2e/group/showGroupsAndClassesInTable.feature
- cypress/e2e/topics/accessH5PEditor.feature
BC-5669
- Added 'unstable_test' tag as a workaround to exclude from the test execution because they are not ready to be run in CI at the moment (by cap team).
> Bc 5669 use unstable tag on the cy test

- cypress/e2e/login_management/invalidCredentials.feature
- cypress/e2e/login_management/passwordUpdate.feature
- cypress/support/pages/login_management/pageLoginManagement.js
- cypress/support/step_definition/login_management/invalidCredentialsSteps.spec.js
the selector was not working anymore because there were multiple forms with this class. So now a data-testid is used, to identify the correct form. Also some corrections following our rules are done in the wording of steps.
https://ticketsystem.dbildungscloud.de/browse/BC-5841
> changed selector with data-testid

- .github/workflows/automatic-trigger.yml
- .github/workflows/main.yml
- .github/workflows/manual-trigger.yml
- .github/workflows/remote-trigger.yml
- .github/workflows/scheduled-trigger.yml
- README.md
- cypress.config.js
- cypress/support/custom_commands/login.js
- scripts/aggregate-json-files.sh
> BC 5468 refactoring 1PW access

- cypress/e2e/dashboard/dashboard.feature
- cypress/e2e/news/readNews.feature
- cypress/support/pages/course/pageCourses.js
- cypress/support/step_definition/authentication/loginStep.spec.js
name of "schools" api changed to "school"
https://ticketsystem.dbildungscloud.de/browse/BC-6067
> BC-6067 - Changed schools to school api

- .github/workflows/automatic-trigger.yml
- .github/workflows/manual-trigger.yml
- .github/workflows/remote-trigger.yml
- .github/workflows/scheduled-trigger.yml
After dev cluster split, we need to update our workflows to properly run tests in CI.
https://ticketsystem.dbildungscloud.de/browse/BC-6124
> BC-6124 update all workflows

- cypress/e2e/admin/administrateAuthentication.feature
- cypress/support/pages/admin/pageAdministration.js
- cypress/support/step_definition/admin/administrateAuthenticationSteps.js
https://ticketsystem.dbildungscloud.de/browse/N21-1497
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/754
https://github.com/hpi-schul-cloud/nuxt-client/pull/2987
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4683
> N21-1497 Add test for warning dialog in system options

- .github/workflows/main.yml
The remote workflow was unable to execute tests due to whitespace errors in the script. The workflow terminated when whitespace was encountered.
> fix - whitespace causing workflow termination and test failure

- cypress/e2e/course/deactivationOfCtlTools.feature
- cypress/e2e/course/showToolOutdated.feature
- cypress/support/pages/admin/pageAdministration.js
- cypress/support/pages/course/pageCourses.js
- cypress/support/step_definition/admin/administrateCtlToolSteps.spec.js
- cypress/support/step_definition/course/toolCourseSteps.spec.js
This PR contains a testflow for the deactivation of ctl tools. 
https://ticketsystem.dbildungscloud.de/browse/N21-1421
> N21-1421 Deactivation of ctl tools

- cypress/e2e/class_management/groupMembers.feature
- cypress/e2e/class_management/showGroupsAndClassesInTable.feature
- cypress/e2e/course/copyCtlTools.feature
- cypress/e2e/course/showToolOutdated.feature
- cypress/support/pages/admin/pageAdministration.js
- cypress/support/pages/course/pageCourses.js
- cypress/support/step_definition/admin/CommonAdministrationSteps.spec.js
- cypress/support/step_definition/authentication/loginStep.spec.js
- cypress/support/step_definition/course/commonCourseSteps.spec.js
- cypress/support/step_definition/course/toolCourseSteps.spec.js
- cypress/support/step_definition/course_management/commonCourseManagementSteps.spec.js
add test for copy ctl tools when copying course
- https://ticketsystem.dbildungscloud.de/browse/N21-1507
> N21-1507 copy ctl tools new

- cypress/e2e/dashboard/dashboard.feature
- cypress/e2e/news/readNews.feature
- cypress/support/e2e.js
- cypress/support/pages/news/pageNews.js
- package-lock.json
- package.json
https://ticketsystem.dbildungscloud.de/browse/BC-5997
- Added a new package 'cypress real event' in order to fix the typing issue in ck5 editor (its a global internal issue on ck side)
- Added some time delay to optimize some page load issue where applicable.
> added package cypress real event to fix ck5 editor type issue in news

- .github/workflows/automatic-trigger.yml
- .github/workflows/main.yml
- .github/workflows/manual-trigger.yml
- .github/workflows/remote-trigger.yml
- .github/workflows/scheduled-trigger.yml
- cypress/e2e/account/goToSettings.feature
- cypress/e2e/class_management/showGroupsAndClassesInTable.feature
- cypress/e2e/course/createEditAndDeleteCourse.feature
- cypress/e2e/teams/teacherAddsEditsDeleteTeamEventWithVideoConference.feature
- cypress/e2e/topics/accessH5PEditor.feature
- cypress/support/custom_commands/login.js
- cypress/support/e2e.js
- cypress/support/pages/login_management/pageLoginManagement.js
- env_variables/template.env.json
- reporter.js
- scripts/aggregate-json-files.sh
As part of the ongoing effort to enhance consistency, we need to update our test automation framework to reflect the recently renamed instance from "DEFAULT" to "DBC". This ensures that our tests accurately reflect the current naming convention and avoid any potential conflicts or confusion.
https://ticketsystem.dbildungscloud.de/browse/BC-6251
> BC-6251 Ensure consistent instance naming

- cypress.config.js
- cypress/e2e/admin/administrateUsers.feature
- cypress/e2e/course/addSubstituteTeacherToCourse.feature
- cypress/e2e/course/createEditAndDeleteCourse.feature
- cypress/e2e/course/searchRoom.feature
- cypress/e2e/dashboard/dashboard.feature
- cypress/e2e/files/myFiles.feature
- cypress/e2e/help-section/helpAreas.feature
- cypress/e2e/learning_store/manageAccessToLearningstore.feature
- cypress/e2e/news/readNews.feature
- cypress/e2e/task/createDeleteTaskFromTaskPage.feature
- cypress/e2e/task/createEditDeleteSubGradFinishRestoreTask.feature
- cypress/e2e/teams/teacherAddsEditsDeleteTeamEventWithVideoConference.feature
- cypress/e2e/teams/teacherCreateEditDeleteTeam.feature
- cypress/e2e/topics/createEditDeleteTopic.feature
- cypress/support/custom_commands/login.js
Cypress tests are failing after log out step.
https://ticketsystem.dbildungscloud.de/browse/BC-6085
> BC-6085 - Investigate - Test fails after log out step

- cypress/e2e/admin/administrateExternalTools.feature
- cypress/e2e/admin/administrateMigration.feature
- cypress/e2e/class_management/showGroupsAndClassesInTable.feature
- cypress/e2e/learning_store/manageAccessToLearningstore.feature
- cypress/e2e/learning_store/searchingLearningstore.feature
- cypress/e2e/teams/teacherAddsEditsDeleteTeamEventWithVideoConference.feature
- cypress/support/pages/admin/pageAdministration.js
- cypress/support/pages/learning_store/pageLearningStore.js
- cypress/support/step_definition/admin/CommonAdministrationSteps.spec.js
- cypress/support/step_definition/admin/administrateCtlToolSteps.spec.js
- cypress/support/step_definition/admin/administrateExternalToolsSteps.spec.js
- cypress/support/step_definition/learning_store/commonLearningStoreSteps.spec.js
- cypress/support/step_definition/learning_store/manageAccessToLearningstoreSteps.spec.js
- cypress/support/step_definition/teams/teacherAddsEditsDeleteTeamEventWithVideoConferenceSteps.spec.js
* created test for searching in learning store
* fixed div tests that weren't running anymore because of removement of old admin page
https://ticketsystem.dbildungscloud.de/browse/BC-6351
> BC-6351 searching learnstore

- cypress/support/pages/tasks/pageTasks.js
Task test had to be adapted because data-testid changed
https://ticketsystem.dbildungscloud.de/browse/BC-6609
> BC-6609 cypress test tasks adapted

- cypress/e2e/class_management/showGroupsAndClassesInTable.feature
- cypress/e2e/course_board/createEditDeleteColumnInBoard.feature
- cypress/e2e/task/createEditDeleteSubGradFinishRestoreTask.feature
- cypress/e2e/topics/createEditDeleteTopic.feature
- cypress/support/pages/admin/pageAdministration.js
- cypress/support/pages/class_management/pageClasses.js
- cypress/support/pages/course/pageCourses.js
- cypress/support/pages/course_board/pageBoard.js
- cypress/support/pages/files/pageFiles.js
- cypress/support/pages/tasks/pageTasks.js
- cypress/support/pages/teams/pageTeams.js
- cypress/support/step_definition/class_management/commonClassesSteps.spec.js
- cypress/support/step_definition/course/commonCourseSteps.spec.js
- cypress/support/step_definition/course_board/createEditDeleteColumnInBoardSteps.spec.js
https://ticketsystem.dbildungscloud.de/browse/BC-6957
- Added new board create scenario in the column tests.
- Refactored the task tests with newly added data-testids
- Refactored the topic tests with newly added data-testids
- Updated the data-testids on different element.
- Updated the api path to /v3 in admin tests/method.
- Removed some api wait().
> BC-6957 Update Board Test and Data-TestIds

- README.md
- cypress.config.js
- cypress/e2e/addons/goToAddons.feature
- cypress/e2e/course/addBBBToolToCourseInNBC.feature
- cypress/support/custom_commands/login.helper.js
- cypress/support/custom_commands/login.js
- cypress/support/pages/course/pageCourses.js
- cypress/support/step_definition/course/commonCourseSteps.spec.js
- env_variables/template.env.json
- package-lock.json
- package.json
- scripts/runSchoolApi.js
We need to implement school api in our cypress framework. For that we need to create a PoC which gives us the first step of how to implemente this api and utilising the artefacts in our test framework. 
https://ticketsystem.dbildungscloud.de/browse/BC-6802
> BC 6802 PoC integrate school api in cypress

- cypress/e2e/course_board/createEditDeleteColumnInBoard.feature
- cypress/e2e/dashboard/dashboard.feature
- cypress/e2e/news/readNews.feature
- cypress/support/pages/course/pageCourses.js
- cypress/support/pages/news/pageNews.js
https://ticketsystem.dbildungscloud.de/browse/BC-7205
> Bc 7205 update news test cases to school api

- cypress/e2e/course/addBBBToolToCourseInNBC.feature
- cypress/e2e/course/addCtlToolToCourse.feature
- cypress/e2e/course/addSubstituteTeacherToCourse.feature
- cypress/e2e/course/searchRoom.feature
- cypress/e2e/course/teacherCreateEditAndDeleteGroupInCourse.feature
- cypress/support/pages/course/pageCourses.js
- cypress/support/step_definition/course/searchRoomSteps.spec.js
- scripts/runSchoolApi.js
After school API implementation, scenarios in Course features needs to be updated.
https://ticketsystem.dbildungscloud.de/browse/BC-7206
- `firstName` & `lastName` in payload according to userType
- Refactor all stable tests for course module
> BC-7206 Update Course feature test cases

- cypress/e2e/course/copyCtlTools.feature
- cypress/e2e/course/deactivationOfCtlTools.feature
- cypress/support/pages/course/pageCourses.js
- cypress/support/step_definition/admin/administrateCtlToolSteps.spec.js
- cypress/support/step_definition/course/toolCourseSteps.spec.js
- https://ticketsystem.dbildungscloud.de/browse/N21-1679
- https://github.com/hpi-schul-cloud/nuxt-client/pull/3230
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/4970
> N21-1679 adjust copyCtlTools test

- cypress/e2e/dashboard/dashboard.feature
- cypress/support/pages/dashboard/pageDashboard.js
- cypress/support/step_definition/dashboard/dashboardSteps.spec.js
https://ticketsystem.dbildungscloud.de/browse/BC-7204
> BC-7204 adapt dashboard tests

- cypress.config.js
- cypress/e2e/course_board/createEditDeleteColumnInBoard.feature
- cypress/e2e/dashboard/dashboard.feature
- cypress/e2e/task/createDeleteTaskFromTaskPage.feature
- cypress/e2e/task/createEditDeleteSubGradFinishRestoreTask.feature
- cypress/e2e/topics/accessH5PEditor.feature
- cypress/e2e/topics/createEditDeleteTopic.feature
- cypress/support/pages/course/pageCourses.js
BC-7285
- Adapted topics related features/tests to the school api.
- Adapted HP5 editor tests and set it as 'stable_test'.
- Some refactoring on Task and Boards tests.
- Adapted viewportWidth to 1500.
> BC-7285 adapt topic tests to school api

- cypress.config.js
- cypress/e2e/course_board/openDrawingElementOnBoard.feature
- cypress/support/pages/course_board/pageBoard.js
- cypress/support/step_definition/course_board/openDrawingElementOnBoardSteps.spec.js
After school API implementation, scenarios in Course Board features needs to be updated.
https://ticketsystem.dbildungscloud.de/browse/BC-7287
> BC-7287 update course board test cases

- cypress/e2e/class_management/groupMembers.feature
- cypress/e2e/class_management/showGroupsAndClassesInTable.feature
- cypress/e2e/course/addCtlToolToCourse.feature
> N21-1914 set test unstable

- cypress/e2e/admin/administrateAuthentication.feature
- cypress/e2e/admin/administrateCtlTools.feature
- cypress/e2e/admin/administrateExternalTools.feature
- cypress/e2e/admin/administrateMigration.feature
- cypress/e2e/admin/administrateUsers.feature
- cypress/e2e/class_management/groupMembers.feature
- cypress/e2e/class_management/showGroupsAndClassesInTable.feature
- cypress/e2e/course/addBBBToolToCourseInBRBDBC.feature
- cypress/e2e/course/addBBBToolToCourseInNBC.feature
- cypress/e2e/course/createEditStopSyncedCourse.feature
- cypress/e2e/course/deactivationOfCtlTools.feature
- cypress/e2e/course_board/createEditDeleteColumnInBoard.feature
- cypress/e2e/learning_store/manageAccessToLearningstore.feature
- cypress/e2e/learning_store/searchingLearningstore.feature
- cypress/e2e/teams/studentCreateEditDeleteTeam.feature
- cypress/e2e/teams/teacherAddsEditsDeleteTeamEventWithVideoConference.feature
- cypress/support/pages/admin/pageAdministration.js
- cypress/support/step_definition/admin/administrateUsersSteps.spec.js
- cypress/support/step_definition/admin/commonAdministrationSteps.spec.js
- fixed admin test to work with new menu structure
- combined methods for teacher and user, so one scenario description for 2 examples (manage teacher and student)
- fixed typo in column board test
https://ticketsystem.dbildungscloud.de/browse/BC-7380
> BC-7380 fix admin test

- cypress/e2e/course/contextRestrictionOfCtlTools.feature
- cypress/e2e/course/copyCtlTools.feature
- cypress/support/pages/admin/pageAdministration.js
- cypress/support/pages/course_board/pageBoard.js
- cypress/support/step_definition/course_board/openDrawingElementOnBoardSteps.spec.js
- https://ticketsystem.dbildungscloud.de/browse/N21-1564
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5085
> N21-1564 ctl tool context restriction

- cypress/e2e/topics/accessH5PEditor.feature
- cypress/e2e/topics/createEditDeleteTopic.feature
- cypress/support/pages/topics/pageTopics.js
- cypress/support/step_definition/topics/createEditDeleteTopic.spec.js
https://ticketsystem.dbildungscloud.de/browse/BC-7641
> Bc 7641 adapt topic test to new breadcrumb

- cypress/e2e/help-section/helpAreas.feature
- cypress/support/pages/help_section/pageHelpSection.js
- cypress/support/step_definition/help_section/commonHelpSectionSteps.spec.js
- cypress/support/step_definition/help_section/helpAreasSteps.spec.js
Steps that used header are removed or changed, because header icons are not available anymore. Also some assertions have been fixed and test data are now defined in the feature file.
https://ticketsystem.dbildungscloud.de/browse/BC-7644
> Bc 7644 adapt help tests

- cypress/e2e/admin/administrateCtlTools.feature
- cypress/e2e/course/addEditDeleteCtlToolInCourse.feature
- cypress/support/pages/admin/pageAdministration.js
- cypress/support/step_definition/admin/administrateCtlToolSteps.spec.js
This is an end to end test for insertion of tools via a url of the tool.
- https://ticketsystem.dbildungscloud.de/browse/N21-2052
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5094
- https://github.com/hpi-schul-cloud/nuxt-client/pull/3313
> N21-2052 add tool via tool link

- cypress/e2e/course/createEditStopSyncedCourse.feature
- cypress/support/pages/admin/pageAdministration.js
- cypress/support/pages/class_management/pageClasses.js
This PR adjust fix and adjust the sync groups of type class tests.
- https://ticketsystem.dbildungscloud.de/browse/N21-1995
> N21-1995 sync course with group test

- cypress/e2e/course_board/createEditDeleteColumnInBoard.feature
- cypress/e2e/dashboard/changeLanguage.feature
BC-7717
- Added @pr tag on the more stable feature files for PR integration.
> BC-7717 tag board tests unstable in ci

- .github/workflows/remote-trigger.yml
- cypress/e2e/admin/administrateAuthentication.feature
- cypress/e2e/admin/administrateCtlTools.feature
- cypress/e2e/admin/administrateExternalTools.feature
- cypress/e2e/admin/administrateMigration.feature
- cypress/e2e/course/addBBBToolToCourseInBRBDBC.feature
- cypress/e2e/course/addBBBToolToCourseInNBC.feature
- cypress/e2e/course/addEditDeleteCtlToolInCourse.feature
- cypress/e2e/course/contextRestrictionOfCtlTools.feature
- cypress/e2e/course/copyCtlTools.feature
- cypress/e2e/course/deactivationOfCtlTools.feature
- cypress/e2e/learning_store/manageAccessToLearningstore.feature
- cypress/e2e/learning_store/searchingLearningstore.feature
- cypress/e2e/mediashelf/useMediaShelf.feature
- cypress/e2e/teams/teacherAddsEditsDeleteTeamEventWithVideoConference.feature
- cypress/support/pages/admin/pageAdministration.js
- cypress/support/step_definition/admin/commonAdministrationSteps.spec.js
BC-7677
- Updated go to administration page for NBC and BRB/dBC related fetures.
- Updated admin page object method.
> BC-7677 update admin steps

- cypress/e2e/help-section/helpAreas.feature
- cypress/support/pages/help_section/pageHelpSection.js
- cypress/support/step_definition/help_section/commonHelpSectionSteps.spec.js
- cypress/support/step_definition/help_section/helpAreasSteps.spec.js
https://ticketsystem.dbildungscloud.de/browse/BC-7814
> Bc 7814 adapt help areas test

- .github/workflows/main.yml
- .github/workflows/manual-trigger.yml
- .github/workflows/remote-trigger.yml
- cypress/e2e/course/createEditAndDeleteCourse.feature
- cypress/e2e/dashboard/dashboard.feature
- cypress/e2e/learning_store/manageAccessToLearningstore.feature
- cypress/e2e/task/createDeleteTaskFromTaskPage.feature
- cypress/e2e/teams/teacherCreateEditDeleteTeam.feature
- cypress/e2e/topics/createEditDeleteTopic.feature
- docs/tags.md
- package.json
BC-7820
- Added parallel tests execution configuration on the manuel trigger and on the remote trigger.
- Grouped the selected feature files into group-A and group-B.
- Added new execution scripts in package.json.
> Bc 7820 parallel tests execution

- cypress/e2e/course_board/deleteDeletedElementOnBoard.feature
- cypress/support/custom_commands/login.js
- cypress/support/pages/course_board/pageBoard.js
- cypress/support/step_definition/course_board/createEditDeleteColumnInBoardSteps.spec.js
- cypress/support/step_definition/course_board/deleteDeletedElementOnBoardSteps.spec.js
- https://ticketsystem.dbildungscloud.de/browse/N21-2031
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5182
- https://github.com/hpi-schul-cloud/nuxt-client/pull/3363
> N21-2031 Placeholder element for deleted tools in boards

- cypress/e2e/course/createEditAndDeleteCourse.feature
- package-lock.json
https://ticketsystem.dbildungscloud.de/browse/BC-7934
> BC-7934 Update dependency

- cypress/e2e/course/createEditStopSyncedCourse.feature
- cypress/e2e/course_management/showCoursesInTable.feature
- cypress/support/pages/admin/pageAdministration.js
- cypress/support/pages/course/pageCourses.js
- cypress/support/pages/course_management/pageCourseManagement.js
- cypress/support/step_definition/course/createEditDeleteSyncedCourseSteps.spec.js
- cypress/support/step_definition/course_management/commonCourseManagementSteps.spec.js
stop course sync from course admin page
- https://ticketsystem.dbildungscloud.de/browse/N21-2174
- https://github.com/hpi-schul-cloud/nuxt-client/pull/3399
> N21-2174 stop course sync from course admin page

- cypress/e2e/files/myFiles.feature
- cypress/support/pages/files/pageFiles.js
- cypress/support/step_definition/files/commonFilesSteps.spec.js
- https://ticketsystem.dbildungscloud.de/browse/BC-7414
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5240
> BC-7414 update files test

- cypress/support/custom_commands/login.js
Currently, login logic based on the asserting staging in the hostname but if branch will contain word staging then it would run wrong login logic.
https://ticketsystem.dbildungscloud.de/browse/BC-8140
> BC-8140 Update logic for login

- cypress/support/pages/tasks/pageTasks.js
Branch test fix for the ticket BC-8214
- Added {force: true} on create task FAB on the task overview page.
> Update pageTasks.js fix for BC-8214 PR

- cypress/e2e/course/copyCtlTools.feature
- https://ticketsystem.dbildungscloud.de/browse/N21-2249
- https://github.com/hpi-schul-cloud/nuxt-client/pull/3448
> N21-2249 student sees incomplete operational alert in board

- cypress/e2e/room/addDeleteParticipants.feature
- cypress/e2e/room/createEditDeleteRoom.feature
- cypress/support/pages/room/pageRooms.js
- cypress/support/step_definition/room/commonRoomSteps.spec.js
- cypress/support/step_definition/room/roomSteps.spec.js
To implement new Room BDD in cypress (CRUD).
BC-8181
https://github.com/hpi-schul-cloud/nuxt-client/pull/3451
- adding scenario tests for room content
> BC-8181 - Implement New Room E2E Test in Cypress

- cypress/e2e/course/deactivationOfCtlTools.feature
- cypress/e2e/mediashelf/deactivationOfCtlToolsInMediaShelf.feature
- cypress/e2e/mediashelf/noAvailableToolsInMediaShelf.feature
- cypress/e2e/mediashelf/useMediaShelf.feature
- cypress/support/pages/mediashelf/pageMediaShelf.js
- cypress/support/step_definition/mediashelf/commonMediaShelfSteps.spec.js
https://ticketsystem.dbildungscloud.de/browse/N21-2048
> N21-2048 deactivation of tools in media shelf

- cypress/support/pages/teams/pageTeams.js
[BC-8494](https://ticketsystem.dbildungscloud.de/browse/BC-8494)
> BC-8494 Video Conference Tests Failing Due to Selector Changes

- cypress/e2e/course/addEditDeleteCtlToolInCourse.feature
- https://ticketsystem.dbildungscloud.de/browse/N21-2328
> N21-2328 fix addEditDeleteCtlInCourse test

- cypress/e2e/course_board/createEditDeleteMultiColumnInBoard.feature
- cypress/e2e/course_board/createEditDeleteSingleColumnBoard.feature
- cypress/e2e/course_board/openDrawingElementOnBoard.feature
- cypress/e2e/room_board/createEditDeleteMultiAndSingleColumnBoardInRoom.feature
- cypress/support/pages/course/pageCourses.js
- cypress/support/pages/course_board/pageBoard.js
- cypress/support/pages/room/pageRooms.js
- cypress/support/pages/room_board/pageRoomBoards.js
- cypress/support/step_definition/course_board/createEditDeleteMultiColumnInBoardSteps.spec.js
- cypress/support/step_definition/room_boards/roomBoardSteps.spec.js
adapt data-testid to renamings board-menu-actions => kebab-menu-actions
BC-8584
https://github.com/hpi-schul-cloud/nuxt-client/pull/3493
> BC-8584 - refactor board menu

- cypress/support/pages/course/pageCourses.js
Fixed data-testid, that was changed in app.
> BC-8717 fixed data-testid

- cypress/e2e/course_board/shareBoardCardLink.feature
- cypress/e2e/room_board/shareBoardCardLinkInRoom.feature
- cypress/support/pages/course_board/pageBoard.js
- cypress/support/pages/room/pageRooms.js
- cypress/support/step_definition/course_board/commonBoardSteps.spec.js
adds test for sharing a link to a board card in courses and rooms
- https://ticketsystem.dbildungscloud.de/browse/N21-2320
- https://github.com/hpi-schul-cloud/nuxt-client/pull/3497
> N21-2320 share links for board cards

- cypress/e2e/task/createSubGradFinishRestoreDeleteTask.feature
- cypress/support/pages/learning_store/pageLearningStore.js
https://ticketsystem.dbildungscloud.de/browse/BC-8852
> BC-8852 searchingLearningstore fails

- cypress/support/pages/admin/pageAdministration.js
- cypress/support/pages/calendar/pageCalendar.js
- cypress/support/pages/class_management/pageClasses.js
- cypress/support/pages/course/pageCourses.js
- cypress/support/pages/dashboard/pageDashboard.js
- cypress/support/pages/files/pageFiles.js
- cypress/support/pages/help_section/pageHelpSection.js
- cypress/support/pages/learning_store/pageLearningStore.js
- cypress/support/pages/mediashelf/pageMediaShelf.js
- cypress/support/pages/news/pageNews.js
- cypress/support/pages/rooms/pageRooms.js
- cypress/support/pages/teams/pageTeams.js
- cypress/support/pages/topics/pageTopics.js
https://ticketsystem.dbildungscloud.de/browse/BC-8658
https://ticketsystem.dbildungscloud.de/browse/BC-8874
> Bc 8658 sidebar data-testids changed

- cypress/support/pages/course/pageCourses.js
https://ticketsystem.dbildungscloud.de/browse/BC-8829
> BC-8829 - linkelement deeplinking

- cypress/e2e/course/addEditDeleteCtlToolInCourse.feature
- cypress/e2e/course/contextRestrictionOfCtlToolsInCourse.feature
- cypress/e2e/course/copyCourseWithCtlTools.feature
- cypress/e2e/course/deactivationOfCtlToolsInCourse.feature
- cypress/e2e/course/shareCourseWithCtlTools.feature
- cypress/e2e/course_board/addEditDeleteCtlToolInBoard.feature
- cypress/e2e/course_board/addPreferredCtlToolInBoard.feature
- cypress/e2e/course_board/contextRestrictionOfCtlToolsInBoard.feature
- cypress/e2e/course_board/copyCourseWithCtlToolsInBoard.feature
- cypress/e2e/course_board/deactivationOfCtlToolsInBoard.feature
- cypress/e2e/mediashelf/contextRestrictionOfCtlToolsInMediaShelf.feature
- cypress/e2e/mediashelf/deactivationOfCtlToolsInMediaShelf.feature
- cypress/e2e/mediashelf/noAvailableToolsInMediaShelf.feature
- cypress/e2e/mediashelf/useMediaShelf.feature
- cypress/support/pages/admin/pageAdministration.js
- cypress/support/pages/admin/pageToolConfiguration.js
- cypress/support/step_definition/admin/ctlToolConfigurationSteps.spec.js
- cypress/support/step_definition/common_helper/prePostConditionCtlSteps.spec.js
- https://ticketsystem.dbildungscloud.de/browse/N21-2518
> N21-2518 add pre post condition for ctl test

- cypress/e2e/course_board/createEditDeleteFolderInCourseBoard.feature
- cypress/e2e/tldraw/createTLdrawWithContent.feature
- cypress/support/step_definition/common_helper/prePostConditionSteps.spec.js
> BC-9537 created test for folder in courseboard

- cypress/e2e/admin/studentManualRegistrationByAdmin.feature
- cypress/support/pages/course_board/pageBoard.js
- cypress/support/pages/room_board/pageRoomBoards.js
[BC-7706](https://ticketsystem.dbildungscloud.de/browse/BC-7706)
> BC-7706 - make titles in board accessible

- cypress/e2e/room_board/addDeleteLinkElementInRoomBoard.feature
- cypress/support/pages/room_board/pageRoomBoards.js
- cypress/support/pages/rooms/pageRooms.js
- cypress/support/step_definition/room_boards/roomBoardSteps.spec.js
BC-9398
- Added feature/test to add Link element in the room board.
> BC-9398 Link Element in Card

- cypress/e2e/room_board/createEditDeleteFolderWithFileUploadInRoomBoard.feature
- cypress/e2e/room_board/uploadMultipleFilesInFolderInRoomBoard.feature
- cypress/e2e/topics/accessH5PEditor.feature
- cypress/support/pages/common_helper/globalActions.js
- cypress/support/pages/common_helper/globalAssertions.js
- cypress/support/pages/room_board/pageRoomBoards.js
- cypress/support/step_definition/common_helper/globalActionSteps.spec.js
- cypress/support/step_definition/common_helper/globalAssertionSteps.spec.js
- cypress/support/step_definition/room_boards/roomBoardSteps.spec.js
> BC-8755 Test for deleting file folder and files inside folder

- cypress/support/pages/course/pageCourses.js
- cypress/support/pages/mediashelf/pageMediaShelf.js
[BC-3480](https://ticketsystem.dbildungscloud.de/browse/BC-3480)
> BC-3480 Empty States

- cypress/e2e/class_management/manageProvisionedGroup.feature
- cypress/e2e/room_board/share_room_board/shareBoardCardLinkInRoom.feature
- cypress/e2e/rooms/addDeleteParticipants.feature
- cypress/e2e/rooms/changeRoomsPermission/changeRoomPermissionViewerToAdmin.feature
- cypress/e2e/rooms/changeRoomsPermission/changeRoomPermissionViewerToEditor.feature
- cypress/e2e/rooms/changeRoomsPermission/changeRoomPermissionViewerToOwner.feature
- cypress/support/pages/rooms/pageRooms.js
[BC-9049](https://ticketsystem.dbildungscloud.de/browse/BC-9049)
> BC-9049 - Change role designations (sidebar/navigation)

- cypress/e2e/room_board/elements_in_board_card/uploadMultipleFilesInFolderInRoomBoard.feature
- cypress/support/pages/room_board/pageRoomBoards.js
- cypress/support/step_definition/room_boards/roomBoardSteps.spec.js
- cypress/support/step_definition/tasks/commonTaskSteps.spec.js
> BC-9723 added zip download of multiple files

- cypress/e2e/course/addEditDeleteCtlToolInCourse.feature
- cypress/e2e/course_board/addEditDeleteCtlToolInBoard.feature
- cypress/e2e/mediashelf/useMediaShelf.feature
- cypress/support/pages/course/pageCourses.js
- cypress/support/pages/course_board/pageBoard.js
- cypress/support/pages/mediashelf/pageMediaShelf.js
- cypress/support/step_definition/course/ctlToolCourseSteps.spec.js
- cypress/support/step_definition/course_board/ctlToolBoardSteps.spec.js
- cypress/support/step_definition/mediashelf/commonMediaShelfSteps.spec.js
- https://ticketsystem.dbildungscloud.de/browse/N21-2417
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5757
- https://github.com/hpi-schul-cloud/nuxt-client/pull/3766
> N21-2417 Add domain info to external tool links

- .github/workflows/automatic-trigger.yml
- .github/workflows/scheduled-trigger.yml
> Quick fix 2

- .github/workflows/scheduled-trigger.yml
> corrected tag typo

- .github/workflows/remote-trigger.yml
> BC-10126 Update remote trigger workflow

- cypress/e2e/course/studentCreateEditAndDeleteGroupInCourse.feature
- cypress/support/pages/course/pageCourses.js
- cypress/support/step_definition/common_helper/prePostConditionSteps.spec.js
- cypress/support/step_definition/course/commonCourseSteps.spec.js
> BC 9990 student creates edits and delets group in course

- cypress/support/pages/room_board/pageRoomBoards.js
- cypress/support/step_definition/common_helper/prePostConditionSteps.spec.js
- cypress/support/step_definition/room_boards/roomBoardSteps.spec.js
> Update prePostConditionSteps.spec.js due to merge conflict in BC-10271

- cypress/e2e/rooms/shareAndImportRoomInSameSchool.feature
- cypress/e2e/rooms/shareAndImportRoomWithDifferentSchoolOnMainDev.feature
- cypress/e2e/rooms/shareAndImportRoomWithDifferentSchoolOnStaging.feature
- cypress/support/step_definition/rooms/roomSteps.spec.js
One test still used the old method and was forgotten to be changed.
BC-10268
old PR: https://github.com/hpi-schul-cloud/e2e-system-tests/pull/369
> BC-10268 - Fixing test

- .github/workflows/main.yml
- .github/workflows/manual-trigger.yml
- cypress.config.js
- cypress/support/pages/admin/pageAdministration.js
https://ticketsystem.dbildungscloud.de/browse/BC-10417
> BC-10417 fix CTL tools test

- cypress/e2e/room_board/share_room_board/shareBoardCardLinkInRoom.feature
- cypress/support/step_definition/common_helper/prePostConditionSteps.spec.js
shareBoardCardLinkInRoom.feature : extend the test case for dbc as well for checking.
BC-10556
> BC-10556 : card highlight issue test cases extend to dbc as well

- cypress/e2e/calendar/addEditDeleteTeamEventCheckInCalendar.feature
- cypress/e2e/teams/studentCreateEditDeleteTeam.feature
- cypress/e2e/teams/teacherAddsEditsDeleteTeamEventWithVideoConference.feature
- cypress/e2e/teams/teacherCreateEditDeleteTeam.feature
- cypress/support/pages/calendar/pageCalendar.js
- cypress/support/pages/teams/pageTeams.js
- cypress/support/step_definition/calendar/commonCalendarSteps.spec.js
- cypress/support/step_definition/common_helper/prePostConditionSteps.spec.js
- cypress/support/step_definition/teams/commonTeamsSteps.spec.js
- cypress/support/step_definition/teams/createEditDeleteTeamSteps.spec.js
- cypress/support/step_definition/teams/teacherAddsEditsDeleteTeamEventWithVideoConferenceSteps.spec.js
> BC-10536 team event in calendar
